package com.firstclub.ops.timeline;

import com.firstclub.reporting.ops.timeline.dto.TimelineEventDTO;
import com.firstclub.reporting.ops.timeline.entity.TimelineEvent;
import com.firstclub.reporting.ops.timeline.service.TimelineService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.List;

/**
 * Ops-layer façade over {@link TimelineService} that provides convenience
 * methods for recording manual timeline entries generated by repair actions,
 * DLQ operations, and mismatch acknowledgements.
 *
 * <p>All write methods swallow exceptions: timeline is <em>derived</em> data
 * and must never roll back the primary operation that triggered it.
 *
 * <p>Read methods delegate transparently to {@link TimelineService}.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class OpsTimelineService {

    private final TimelineService        timelineService;
    private final TimelineEventFactory   factory;

    // ── Read ──────────────────────────────────────────────────────────────────

    /**
     * Returns the full timeline for a specific entity in descending event-time order.
     *
     * @param merchantId tenant scope
     * @param entityType one of the {@link com.firstclub.reporting.ops.timeline.entity.TimelineEntityTypes} constants
     * @param entityId   primary key of the entity
     */
    public List<TimelineEventDTO> getEntityTimeline(Long merchantId, String entityType, Long entityId) {
        return timelineService.getTimelineForEntity(merchantId, entityType, entityId);
    }

    // ── Write — ops repair events ─────────────────────────────────────────────

    /** Record that an outbox event was manually requeued. */
    public void recordOutboxRetry(Long eventId, Long merchantId, String actorContext) {
        appendSafe(factory.forOutboxRetry(eventId, merchantId, actorContext));
    }

    /** Record that a webhook delivery was manually reset for retry. */
    public void recordWebhookRetry(Long deliveryId, Long merchantId, String actorContext) {
        appendSafe(factory.forWebhookRetry(deliveryId, merchantId, actorContext));
    }

    /** Record that reconciliation was manually re-run for a date. */
    public void recordReconRerun(LocalDate date, Long merchantId, String actorContext) {
        appendSafe(factory.forReconRerun(date, merchantId, actorContext));
    }

    /** Record that an invoice's totals were rebuilt from its line items. */
    public void recordInvoiceRebuild(Long invoiceId, Long merchantId, String actorContext) {
        appendSafe(factory.forInvoiceRebuild(invoiceId, merchantId, actorContext));
    }

    /** Record that the ledger balance snapshot was rebuilt for a date. */
    public void recordLedgerRebuild(Long merchantId, String dateStr, String actorContext) {
        appendSafe(factory.forLedgerRebuild(merchantId, dateStr, actorContext));
    }

    /** Record that a DLQ message was re-enqueued to the outbox. */
    public void recordDlqRequeue(Long dlqId, Long merchantId, String actorContext) {
        appendSafe(factory.forDlqRequeue(dlqId, merchantId, actorContext));
    }

    /** Record that a reconciliation mismatch was acknowledged. */
    public void recordMismatchAcknowledge(Long mismatchId, Long merchantId, String actorContext) {
        appendSafe(factory.forMismatchAcknowledge(mismatchId, merchantId, actorContext));
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    private void appendSafe(TimelineEvent event) {
        try {
            timelineService.appendManual(event);
        } catch (Exception ex) {
            log.warn("OpsTimeline: failed to record event type={} entity={}/{}: {}",
                    event.getEventType(), event.getEntityType(), event.getEntityId(), ex.getMessage());
        }
    }
}
