package com.firstclub.ledger.revenue.service;

import com.firstclub.ledger.revenue.dto.RevenueRecognitionRunResponseDTO;

import java.time.LocalDate;

public interface RevenueRecognitionPostingService {

    /**
     * Finds all PENDING schedules whose {@code recognition_date} is on or before {@code date}
     * and posts a ledger entry for each one.
     *
     * <p>Each posting is isolated in its own transaction ({@code REQUIRES_NEW}).
     * A failure on one schedule does not prevent the others from being processed;
     * the failed schedule remains {@code PENDING} so it can be retried on the next run.
     * This makes re-running the same date fully idempotent.
     *
     * <p>Phase 14: a monotonic {@code posting_run_id} is generated at the start of
     * each invocation ({@code System.currentTimeMillis()}) and stored on every schedule
     * row posted in that run, enabling per-run audit queries.
     *
     * @param date upper-bound recognition date (inclusive)
     * @return summary containing counts of posted / failed schedules
     */
    RevenueRecognitionRunResponseDTO postDueRecognitionsForDate(LocalDate date);

    /**
     * Posts a single recognition schedule row.  Idempotent: if the schedule is
     * already POSTED the method returns without touching the ledger.
     * Runs in a dedicated {@code REQUIRES_NEW} transaction so that a ledger failure
     * only rolls back this one row, not the whole batch.
     *
     * @param scheduleId the schedule to post
     */
    void postSingleRecognition(Long scheduleId);

    /**
     * Posts a single recognition schedule row within a named batch run.
     *
     * <p>Identical to {@link #postSingleRecognition(Long)} but additionally
     * stamps {@code postingRunId} on the row, allowing operators to query
     * "all rows posted in run X".  Used internally by
     * {@link #postDueRecognitionsForDate(LocalDate)}.
     *
     * <p>Runs in a dedicated {@code REQUIRES_NEW} transaction.
     *
     * @param scheduleId  the schedule to post
     * @param postingRunId monotonic run identifier generated by the batch method
     */
    void postSingleRecognitionInRun(Long scheduleId, Long postingRunId);
}
